### ISSUE TITLE
Include 25x100 sensor in the monitor 

### ISSUE THREAD

**Issue by duartej** [duartej/eudaq#8]
Deal with the 25x100 layout chip

**Comment by duartej** [comment]
Constructor of [EUTelRD53ADetector](https://github.com/duartej/eudaq/blob/v1.x-dev/nreader/detdescription/EUTelRD53ADetector.cc ) accepts as arguments the x,y pitch
But so far its defines the x and y columns as fixed. This should change, and define the X and Y min and max pixel, instead it should defined x,y size

**Comment by duartej** [comment]
Proposed change in constructor
```c++
static float X_SIZE=20.0; // mm
static float Y_SIZE=9.6; // mm
EUTelRD53ADetector::EUTelRD53ADetector(float xpitch_mm, float ypitch_mm)
    : EUTelPixelDetector() 
{
    _xPitch = xpitch_mm; // mm
    _yPitch = ypitch_mm; // mm

    _xMin = 0;
    _xMax = int(X_SIZE/_xPitch)-1;
    
    _yMin = 0;
    _yMax = int(Y_SIZE/_yPitch)-1;
    
    _name = "RD53A";    
}
```

**Comment by duartej** [comment]
The ```EUTelRD53ADetector``` class is instantiated in the [BDAQ53ConverterPlugin](https://github.com/duartej/eudaq/blob/v1.x-dev/main/lib/plugins/BDAQ53ConverterPlugin.cc#L258), which means that the information of the pitch should be stored in the file header, via the ```setTag``` mechanism in the [PyProducer](https://github.com/duartej/eudaq/blob/v1.x-dev/main/python/src/PyProducer.cpp#L39) implementation (L39, should be done at each event, as in principle is prepared to have more than one sensor per board). 
The pitch could be implemented at the configuration file (.conf), being the default value 50x50

This approach needs the information to be in the file (header), therefore if the file was created without
the info, there is no way to include it .... **how to process the available data** (without hardcoding things?)

**Comment by duartej** [comment]
The mapping from the data collected (RD53A chip columns and rows) to real geometric pixel position (which makes sense process the data) is based on on the followed figure (providded by M. Meschini)
![marco_skecth_25100](https://user-images.githubusercontent.com/1272673/46080533-7b25cf80-c19a-11e8-9db9-2fdbf02b0aae.png)

This figure should be flipped in order to include the reflection of the chip layout when is bump-bonded to the sensor.  After the reflection, 

<img src="https://user-images.githubusercontent.com/1272673/46081841-d3120580-c19d-11e8-9c45-f3f8d2af4f1a.png" width="200">

The mapping becomes then,

* ![codecogseqn](https://user-images.githubusercontent.com/1272673/46082627-cbebf700-c19f-11e8-84fe-b2526fcc8466.png)
* ![codecogseqn_2](https://user-images.githubusercontent.com/1272673/46082699-f6d64b00-c19f-11e8-8bb6-64e871198749.png)

**Comment by duartej** [comment]
Looks like the previous image (the one from Meschini) was already fillped, therefore the other image is not right, instead, the map is: 
* ROC(0,0) --> PIX(0,0)     ROC(0,1) --> PIX(1,0) 

Then the lower image from the last entry is upside-down. Therefore the proper mapping  is:
*![codecogseqn_fixed](https://user-images.githubusercontent.com/1272673/46094511-783ad700-c1ba-11e8-89c1-f2428b04c5da.png)
*![codecogseqn_fixed_col](https://user-images.githubusercontent.com/1272673/46095247-5b9f9e80-c1bc-11e8-8324-0bb039d019ed.png)

**Comment by duartej** [comment]
Commit  391502fdc2 includes the implementation of the 25x100 layout. Before closing this issues, I want to validate (some checks done, but not deeply)

 The layout must be introduced with the new configuration field:  ```layout_DUT#```, where ```#``` is the DUT ID (board id of the ```scan_eudaq```). The field should be under the section ```[bdaq53a.Producer]```. For instance, assuming we have the DUT 3 with the layout 25x100, we should update the config file for run Control:
```bash
[bdaq53a.Producer]
layout_DUT3="25x100"
```
Note that is not needed to specify layouts "50x50" as they are taken as defaults. 
**IMPORTANT** 
It is implemented an offline mechanism for backward compatibility with data already taken, and to be able to correct a potential misconfiguration when running online. In order to be change the layout ***offline***, in the working directory (when run ```jobsub```, ```Converter.exe```, ```OnlineMon.exe``` or whatever exec ), the configuration file **exactly named** ```sensor_layouts_offline.cfg``` must be put in place with the same syntax than the online config mentioned above.

**Comment by ZhangGang00** [comment]
Dear Jordi,

Thanks for extending eudaq to 25*100 sensor! I am working with test beam analysis with 25*100 pixel sensor using Eutelescope. I have updated the latest eutelescope and eudaq, and followed your instruction. But it seems not to work: 

**23:10:30 jobsub.converter(ERROR): [ ERROR5 "NoisyPixelMaskerAPIX"] Pixel: 368|175 on plane: 21 fired.
23:10:30 jobsub.converter(ERROR): [ ERROR5 "NoisyPixelMaskerAPIX"] This pixel is out of the range defined by the geometry. Either your data is corrupted or your pixel geometry not specified correctly!
23:10:30 jobsub.converter(ERROR): [ ERROR5 "NoisyPixelMaskerAPIX"] Pixel: 368|174 on plane: 21 fired.
23:10:30 jobsub.converter(ERROR): [ ERROR5 "NoisyPixelMaskerAPIX"] This pixel is out of the range defined by the geometry. Either your data is corrupted or your pixel geometry not specified correctly!**

I attached some relevant files. Could you please help me to figure it out?

Best,
Gang
[Archive.zip](https://github.com/duartej/eudaq/files/2825005/Archive.zip)

**Comment by duartej** [comment]
@ZhangGang00 , I realized I deleted your comment unintentionally.  
The output you sent is typically saying that you are using a wrong geometry layout in the gear geometry file. You have to be sure that you have tagged your sensors as 25x100 if is the case (see https://github.com/duartej/eudaq/issues/8#issuecomment-425256633 ) and the gear file MUST have as well this information. Be sure you are describing properly your DUT in the gear file.

**Comment by ZhangGang00** [comment]
Hi Jordi,

Thanks for the reply! I think the problem is that I need to use YarrConverterPlugin. Do you know if anyone has included 25*100 sensor in YarrConverterPlugin?

Thanks,
Gang

**Comment by duartej** [comment]
If you took your data with yarr, then yes, you must use some yarr converter, which I don't know if exist (I presume yes, but I don't know).
